// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5179' | (string & {});
};

export type AnalyticsBreakdown = {
    dimension: AnalyticsDimension;
    rows: Array<AnalyticsBreakdownRow>;
};

export type AnalyticsBreakdownRow = {
    value: string;
    pageViews: number;
    visitors: number;
};

export type AnalyticsConnectionSettingsResponse = {
    alias: string;
    displayName: string;
    projectId: string;
    teamId?: string | null;
    teamSlug?: string | null;
    hostnames: Array<string>;
    documentRootKeys: Array<string>;
    enableAllDocumentTypes: boolean;
    enabledDocumentTypeKeys: Array<string>;
    hasAccessToken: boolean;
};

export type AnalyticsConnectionSummary = {
    alias: string;
    displayName: string;
    isDefault: boolean;
    isConfigured: boolean;
    hostnames: Array<string>;
    warnings: Array<string>;
};

export type AnalyticsConnectionTestResult = {
    success: boolean;
    message: string;
};

export type AnalyticsConnectionsResponse = {
    enabled: boolean;
    defaultConnection?: string | null;
    defaultRangeDays: number;
    connections: Array<AnalyticsConnectionSummary>;
};

export type AnalyticsDimension = 'RequestPath' | 'Route' | 'ReferrerHostname' | 'Country' | 'DeviceType' | 'BrowserName' | 'OsName' | 'UtmSource' | 'UtmMedium' | 'UtmCampaign';

export type AnalyticsDocumentRoute = {
    connection: string;
    culture: string;
    hostname: string;
    path: string;
    url: string;
    isCurrent: boolean;
    warnings: Array<string>;
};

export type AnalyticsInterval = 'Day' | 'Week' | 'Month';

export type AnalyticsPoint = {
    timestamp: string;
    pageViews: number;
    visitors: number;
};

export type AnalyticsSettingsResponse = {
    enabled: boolean;
    defaultConnection?: string | null;
    defaultRangeDays: number;
    cacheDuration: string;
    connections: Array<AnalyticsConnectionSettingsResponse>;
};

export type AnalyticsSummary = {
    totals: AnalyticsTotals;
    points: Array<AnalyticsPoint>;
};

export type AnalyticsTotals = {
    pageViews: number;
    visitors: number;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type UpdateAnalyticsConnectionRequest = {
    alias: string;
    displayName: string;
    projectId: string;
    teamId?: string | null;
    teamSlug?: string | null;
    hostnames: Array<string>;
    documentRootKeys: Array<string>;
    enableAllDocumentTypes: boolean;
    enabledDocumentTypeKeys: Array<string>;
};

export type UpdateAnalyticsSettingsRequest = {
    enabled: boolean;
    defaultConnection?: string | null;
    defaultRangeDays: number;
    cacheDuration: string;
    connections: Array<UpdateAnalyticsConnectionRequest>;
};

export type ConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/vercel-analytics/connections';
};

export type ConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ConnectionsResponses = {
    /**
     * OK
     */
    200: AnalyticsConnectionsResponse;
};

export type ConnectionsResponse = ConnectionsResponses[keyof ConnectionsResponses];

export type DocumentRoutesData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: {
        culture?: string;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/documents/{documentId}/routes';
};

export type DocumentRoutesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type DocumentRoutesResponses = {
    /**
     * OK
     */
    200: Array<AnalyticsDocumentRoute>;
};

export type DocumentRoutesResponse = DocumentRoutesResponses[keyof DocumentRoutesResponses];

export type BreakdownData = {
    body?: never;
    path: {
        dimension: AnalyticsDimension;
    };
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        limit?: number;
        documentId?: string;
        culture?: string;
        path?: string;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/reports/breakdown/{dimension}';
};

export type BreakdownErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type BreakdownResponses = {
    /**
     * OK
     */
    200: AnalyticsBreakdown;
};

export type BreakdownResponse = BreakdownResponses[keyof BreakdownResponses];

export type SummaryData = {
    body?: never;
    path?: never;
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        documentId?: string;
        culture?: string;
        path?: string;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/reports/summary';
};

export type SummaryErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SummaryResponses = {
    /**
     * OK
     */
    200: AnalyticsSummary;
};

export type SummaryResponse = SummaryResponses[keyof SummaryResponses];

export type SettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/vercel-analytics/settings';
};

export type SettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SettingsResponses = {
    /**
     * OK
     */
    200: AnalyticsSettingsResponse;
};

export type SettingsResponse = SettingsResponses[keyof SettingsResponses];

export type SaveSettingsData = {
    body?: UpdateAnalyticsSettingsRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/vercel-analytics/settings';
};

export type SaveSettingsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SaveSettingsResponses = {
    /**
     * OK
     */
    200: AnalyticsSettingsResponse;
};

export type SaveSettingsResponse = SaveSettingsResponses[keyof SaveSettingsResponses];

export type TestConnectionData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/vercel-analytics/settings/connections/{alias}/test';
};

export type TestConnectionErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type TestConnectionResponses = {
    /**
     * OK
     */
    200: AnalyticsConnectionTestResult;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];
