// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44389' | (string & {});
};

export type AnalyticsBreakdown = {
    dimension: AnalyticsDimension;
    rows: Array<AnalyticsBreakdownRow>;
};

export type AnalyticsBreakdownRow = {
    value: string;
    pageViews: number;
    visitors: number;
};

export type AnalyticsConnectionSettingsResponse = {
    key: string;
    displayName: string;
    projectId: string;
    team?: string | null;
    documentRootKeys: Array<string>;
    enableAllDocumentTypes: boolean;
    enabledDocumentTypeKeys: Array<string>;
    hasAccessToken: boolean;
    hasAccessTokenOverride: boolean;
};

export type AnalyticsConnectionSummary = {
    key: string;
    displayName: string;
    isDefault: boolean;
    isConfigured: boolean;
    baseUrl?: string | null;
    warnings: Array<string>;
};

export type AnalyticsConnectionTestResult = {
    success: boolean;
    message: string;
};

export type AnalyticsConnectionsResponse = {
    enabled: boolean;
    defaultRangeDays: number;
    connections: Array<AnalyticsConnectionSummary>;
};

export type AnalyticsDimension = 'RequestPath' | 'Route' | 'ReferrerHostname' | 'Country' | 'DeviceType' | 'BrowserName' | 'OsName' | 'UtmSource' | 'UtmMedium' | 'UtmCampaign' | 'UtmTerm' | 'UtmContent' | 'EventName';

export type AnalyticsDocumentRoute = {
    connection: string;
    culture: string;
    hostname: string;
    path: string;
    url: string;
    isCurrent: boolean;
    warnings: Array<string>;
};

export type AnalyticsEventDetails = {
    eventName: string;
    totals: AnalyticsEventTotals;
    properties: Array<AnalyticsEventProperty>;
};

export type AnalyticsEventProperty = {
    name: string;
    values: Array<AnalyticsEventPropertyValue>;
};

export type AnalyticsEventPropertyValue = {
    value: string;
    count: number;
    visitors: number;
};

export type AnalyticsEventRow = {
    eventName: string;
    count: number;
    visitors: number;
};

export type AnalyticsEventTotals = {
    count: number;
    visitors: number;
};

export type AnalyticsEventsReport = {
    rows: Array<AnalyticsEventRow>;
};

export type AnalyticsFlagRow = {
    value: string;
    pageViews: number;
    visitors: number;
};

export type AnalyticsFlagsReport = {
    flagKey?: string | null;
    rows: Array<AnalyticsFlagRow>;
};

export type AnalyticsInterval = 'Hour' | 'Day' | 'Week' | 'Month';

export type AnalyticsPoint = {
    timestamp: string;
    pageViews: number;
    visitors: number;
};

export type AnalyticsProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    code: string;
};

export type AnalyticsSettingsResponse = {
    enabled: boolean;
    hasAccessToken: boolean;
    defaultRangeDays: number;
    cacheDuration: string;
    connections: Array<AnalyticsConnectionSettingsResponse>;
};

export type AnalyticsSummary = {
    totals: AnalyticsTotals;
    previousTotals?: AnalyticsTotals | null;
    points: Array<AnalyticsPoint>;
};

export type AnalyticsTotals = {
    pageViews: number;
    visitors: number;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type UpdateAnalyticsConnectionRequest = {
    key: string;
    displayName: string;
    projectId: string;
    team?: string | null;
    documentRootKeys: Array<string>;
    enableAllDocumentTypes: boolean;
    enabledDocumentTypeKeys: Array<string>;
};

export type UpdateAnalyticsSettingsRequest = {
    enabled: boolean;
    defaultRangeDays: number;
    cacheDuration: string;
    connections: Array<UpdateAnalyticsConnectionRequest>;
};

export type ConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/vercel-analytics/connections';
};

export type ConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ConnectionsResponses = {
    /**
     * OK
     */
    200: AnalyticsConnectionsResponse;
};

export type ConnectionsResponse = ConnectionsResponses[keyof ConnectionsResponses];

export type DocumentRoutesData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: {
        culture?: string;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/documents/{documentId}/routes';
};

export type DocumentRoutesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type DocumentRoutesResponses = {
    /**
     * OK
     */
    200: Array<AnalyticsDocumentRoute>;
};

export type DocumentRoutesResponse = DocumentRoutesResponses[keyof DocumentRoutesResponses];

export type BreakdownData = {
    body?: never;
    path: {
        dimension: AnalyticsDimension;
    };
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        limit?: number;
        search?: string;
        documentId?: string;
        culture?: string;
        path?: string;
        filter?: Array<string>;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/reports/breakdown/{dimension}';
};

export type BreakdownErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    400: AnalyticsProblemDetails;
    402: AnalyticsProblemDetails;
    404: AnalyticsProblemDetails;
    502: AnalyticsProblemDetails;
    503: AnalyticsProblemDetails;
    504: AnalyticsProblemDetails;
};

export type BreakdownResponses = {
    /**
     * OK
     */
    200: AnalyticsBreakdown;
};

export type BreakdownResponse = BreakdownResponses[keyof BreakdownResponses];

export type EventsData = {
    body?: never;
    path?: never;
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        limit?: number;
        search?: string;
        documentId?: string;
        culture?: string;
        path?: string;
        filter?: Array<string>;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/reports/events';
};

export type EventsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    400: AnalyticsProblemDetails;
    402: AnalyticsProblemDetails;
    404: AnalyticsProblemDetails;
    502: AnalyticsProblemDetails;
    503: AnalyticsProblemDetails;
    504: AnalyticsProblemDetails;
};

export type EventsResponses = {
    /**
     * OK
     */
    200: AnalyticsEventsReport;
};

export type EventsResponse = EventsResponses[keyof EventsResponses];

export type FlagsData = {
    body?: never;
    path?: never;
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        flagKey?: string;
        limit?: number;
        documentId?: string;
        culture?: string;
        path?: string;
        filter?: Array<string>;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/reports/flags';
};

export type FlagsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    400: AnalyticsProblemDetails;
    402: AnalyticsProblemDetails;
    404: AnalyticsProblemDetails;
    502: AnalyticsProblemDetails;
    503: AnalyticsProblemDetails;
    504: AnalyticsProblemDetails;
};

export type FlagsError = FlagsErrors[keyof FlagsErrors];

export type FlagsResponses = {
    /**
     * OK
     */
    200: AnalyticsFlagsReport;
};

export type FlagsResponse = FlagsResponses[keyof FlagsResponses];

export type EventDetailsData = {
    body?: never;
    path?: never;
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        eventName?: string;
        eventProperty?: string;
        eventValue?: string;
        documentId?: string;
        culture?: string;
        path?: string;
        filter?: Array<string>;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/reports/events/details';
};

export type EventDetailsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    400: AnalyticsProblemDetails;
    402: AnalyticsProblemDetails;
    404: AnalyticsProblemDetails;
    502: AnalyticsProblemDetails;
    503: AnalyticsProblemDetails;
    504: AnalyticsProblemDetails;
};

export type EventDetailsResponses = {
    /**
     * OK
     */
    200: AnalyticsEventDetails;
};

export type EventDetailsResponse = EventDetailsResponses[keyof EventDetailsResponses];

export type EventPropertyValuesData = {
    body?: never;
    path?: never;
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        eventName?: string;
        propertyName?: string;
        limit?: number;
        search?: string;
        eventProperty?: string;
        eventValue?: string;
        documentId?: string;
        culture?: string;
        path?: string;
        filter?: Array<string>;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/reports/events/property-values';
};

export type EventPropertyValuesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    400: AnalyticsProblemDetails;
    402: AnalyticsProblemDetails;
    404: AnalyticsProblemDetails;
    502: AnalyticsProblemDetails;
    503: AnalyticsProblemDetails;
    504: AnalyticsProblemDetails;
};

export type EventPropertyValuesResponses = {
    /**
     * OK
     */
    200: AnalyticsEventProperty;
};

export type EventPropertyValuesResponse = EventPropertyValuesResponses[keyof EventPropertyValuesResponses];

export type SummaryData = {
    body?: never;
    path?: never;
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        documentId?: string;
        culture?: string;
        path?: string;
        filter?: Array<string>;
    };
    url: '/umbraco/management/api/v1/vercel-analytics/reports/summary';
};

export type SummaryErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    400: AnalyticsProblemDetails;
    402: AnalyticsProblemDetails;
    404: AnalyticsProblemDetails;
    502: AnalyticsProblemDetails;
    503: AnalyticsProblemDetails;
    504: AnalyticsProblemDetails;
};

export type SummaryResponses = {
    /**
     * OK
     */
    200: AnalyticsSummary;
};

export type SummaryResponse = SummaryResponses[keyof SummaryResponses];

export type SettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/vercel-analytics/settings';
};

export type SettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SettingsResponses = {
    /**
     * OK
     */
    200: AnalyticsSettingsResponse;
};

export type SettingsResponse = SettingsResponses[keyof SettingsResponses];

export type SaveSettingsData = {
    body?: UpdateAnalyticsSettingsRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/vercel-analytics/settings';
};

export type SaveSettingsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SaveSettingsResponses = {
    /**
     * OK
     */
    200: AnalyticsSettingsResponse;
};

export type SaveSettingsResponse = SaveSettingsResponses[keyof SaveSettingsResponses];

export type TestConnectionData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/vercel-analytics/settings/connections/{key}/test';
};

export type TestConnectionErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type TestConnectionResponses = {
    /**
     * OK
     */
    200: AnalyticsConnectionTestResult;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];
