// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { BreakdownData, BreakdownErrors, BreakdownResponses, ConnectionsData, ConnectionsErrors, ConnectionsResponses, DocumentRoutesData, DocumentRoutesErrors, DocumentRoutesResponses, EventDetailsData, EventDetailsErrors, EventDetailsResponses, EventPropertyValuesData, EventPropertyValuesErrors, EventPropertyValuesResponses, EventsData, EventsErrors, EventsResponses, FlagsData, FlagsErrors, FlagsResponses, SaveSettingsData, SaveSettingsErrors, SaveSettingsResponses, SettingsData, SettingsErrors, SettingsResponses, SummaryData, SummaryErrors, SummaryResponses, TestConnectionData, TestConnectionErrors, TestConnectionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class TheBuilderWebAnalyticsService {
    public static connections<ThrowOnError extends boolean = false>(options?: Options<ConnectionsData, ThrowOnError>): RequestResult<ConnectionsResponses, ConnectionsErrors, ThrowOnError> {
        return (options?.client ?? client).get<ConnectionsResponses, ConnectionsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/connections',
            ...options
        });
    }

    public static documentRoutes<ThrowOnError extends boolean = false>(options: Options<DocumentRoutesData, ThrowOnError>): RequestResult<DocumentRoutesResponses, DocumentRoutesErrors, ThrowOnError> {
        return (options.client ?? client).get<DocumentRoutesResponses, DocumentRoutesErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/documents/{documentId}/routes',
            ...options
        });
    }

    public static breakdown<ThrowOnError extends boolean = false>(options: Options<BreakdownData, ThrowOnError>): RequestResult<BreakdownResponses, BreakdownErrors, ThrowOnError> {
        return (options.client ?? client).get<BreakdownResponses, BreakdownErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/reports/breakdown/{dimension}',
            ...options
        });
    }

    public static events<ThrowOnError extends boolean = false>(options?: Options<EventsData, ThrowOnError>): RequestResult<EventsResponses, EventsErrors, ThrowOnError> {
        return (options?.client ?? client).get<EventsResponses, EventsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/reports/events',
            ...options
        });
    }

    public static eventDetails<ThrowOnError extends boolean = false>(options?: Options<EventDetailsData, ThrowOnError>): RequestResult<EventDetailsResponses, EventDetailsErrors, ThrowOnError> {
        return (options?.client ?? client).get<EventDetailsResponses, EventDetailsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/reports/events/details',
            ...options
        });
    }

    public static eventPropertyValues<ThrowOnError extends boolean = false>(options?: Options<EventPropertyValuesData, ThrowOnError>): RequestResult<EventPropertyValuesResponses, EventPropertyValuesErrors, ThrowOnError> {
        return (options?.client ?? client).get<EventPropertyValuesResponses, EventPropertyValuesErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/reports/events/property-values',
            ...options
        });
    }

    public static flags<ThrowOnError extends boolean = false>(options?: Options<FlagsData, ThrowOnError>): RequestResult<FlagsResponses, FlagsErrors, ThrowOnError> {
        return (options?.client ?? client).get<FlagsResponses, FlagsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/reports/flags',
            ...options
        });
    }

    public static summary<ThrowOnError extends boolean = false>(options?: Options<SummaryData, ThrowOnError>): RequestResult<SummaryResponses, SummaryErrors, ThrowOnError> {
        return (options?.client ?? client).get<SummaryResponses, SummaryErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/reports/summary',
            ...options
        });
    }

    public static settings<ThrowOnError extends boolean = false>(options?: Options<SettingsData, ThrowOnError>): RequestResult<SettingsResponses, SettingsErrors, ThrowOnError> {
        return (options?.client ?? client).get<SettingsResponses, SettingsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/settings',
            ...options
        });
    }

    public static saveSettings<ThrowOnError extends boolean = false>(options?: Options<SaveSettingsData, ThrowOnError>): RequestResult<SaveSettingsResponses, SaveSettingsErrors, ThrowOnError> {
        return (options?.client ?? client).put<SaveSettingsResponses, SaveSettingsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/settings',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

    public static testConnection<ThrowOnError extends boolean = false>(options: Options<TestConnectionData, ThrowOnError>): RequestResult<TestConnectionResponses, TestConnectionErrors, ThrowOnError> {
        return (options.client ?? client).post<TestConnectionResponses, TestConnectionErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/management/api/v1/web-analytics/settings/connections/{key}/test',
            ...options
        });
    }
}
